apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-apps-test2
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx2
          image: ngint:1.14.2
          ports:
            - containerPort: 80
