apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: helm-guestbook
    name: dev-cluster
  project: default
  source:
    path: app1
    repoURL: http://10.0.1.100:8000/git/namla/namla-apps.git
    targetRevision: HEAD